#!/bin/bash
sed -i "/annotations\:/d"  deploy.yaml
sed -i "/deployment\.kubernetes\.io/d"  deploy.yaml
sed -i "/creationTimestamp/d"  deploy.yaml
sed -i "/generation\:/d"  deploy.yaml
sed -i "/namespace\:/d"  deploy.yaml
sed -i "/resourceVersion\:/d"  deploy.yaml
sed -i "/selfLink\:/d"  deploy.yaml
sed -i "/progressDeadlineSeconds\:/d"  deploy.yaml
sed -i "/replicas\:/d"  deploy.yaml
sed -i "/revisionHistoryLimit\:/d"  deploy.yaml
sed -i "/strategy\:/d"  deploy.yaml
sed -i "/rollingUpdate\:/d"  deploy.yaml
sed -i "/maxSurge\:/d"  deploy.yaml
sed -i "/maxUnavailable\:/d"  deploy.yaml
sed -i "/RollingUpdate/d"  deploy.yaml
sed -i "/creationTimestamp\:/d"  deploy.yaml
sed -i "/imagePullPolicy\:/d"  deploy.yaml
sed -i "/resources\:/d"  deploy.yaml
sed -i "/securityContext\:/d"  deploy.yaml
sed -i "/privileged\:/d"  deploy.yaml
sed -i "/terminationMessagePath\:/d"  deploy.yaml
sed -i "/terminationMessagePolicy/d"  deploy.yaml
sed -i "/dnsPolicy/d"  deploy.yaml
sed -i "/nodeSelector/d"  deploy.yaml
sed -i "/sys_type/d"  deploy.yaml
sed -i "/restartPolicy/d"  deploy.yaml
sed -i "/schedulerName/d"  deploy.yaml
sed -i "/securityContext/d"  deploy.yaml
sed -i "/terminationGracePeriodSeconds/d"  deploy.yaml
sed -i "/status\:/d"  deploy.yaml
sed -i "/availableReplicas/d"  deploy.yaml
sed -i "/conditions\:/d"  deploy.yaml
sed -i "/lastTransitionTime/d"  deploy.yaml
sed -i "/lastUpdateTime/d"  deploy.yaml
sed -i "/message/d"  deploy.yaml
sed -i "/reason/d"  deploy.yaml
sed -i "/Available/d"  deploy.yaml
sed -i "/lastTransitionTime/d"  deploy.yaml
sed -i "/lastUpdateTime/d"  deploy.yaml
sed -i "/message/d"  deploy.yaml
sed -i "/reason/d"  deploy.yaml
sed -i "/Progressing/d"  deploy.yaml
sed -i "/Progressing/d"  deploy.yaml
sed -i "/readyReplicas/d"  deploy.yaml
sed -i "/replicas/d"  deploy.yaml
sed -i "/updatedReplicas/d"  deploy.yaml
sed -i "/observedGeneration/d" deploy.yaml
sed -i "/collisionCount/d" deploy.yaml
